services:
  mysql:
    image: mysql:latest
    container_name: pw_mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: motdepasse
    volumes:
      - pw_database:/var/lib/mysql:Z
    restart: always

  phpmyadmin:
    image: phpmyadmin
    container_name: pw_phpmyadmin
    ports:
      - '8080:80'
    links:
      - mysql:db
    restart: always

volumes:
  pw_database:
    external: true
    name: mysql_data
