services:
  database:
    image: mysql:latest
    container_name: pw_mysql
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: motdepasse
    volumes:
      - mysql_data:/var/lib/mysql:Z
    restart: always

  phpmyadmin:
    image: phpmyadmin
    container_name: pw_phpmyadmin
    ports:
      - '8080:80'
    links:
      - database:db
    restart: always

volumes:
  mysql_data:
    external: true
    name: mysql_data
